language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  # APCu vs APCu
  - if [[ "$(php -v | grep 'PHP 5')" ]]; then yes | pecl install -f apcu-4.0.8; fi
  - if [[ "$(php -v | grep 'PHP 7')" ]]; then yes | pecl install -f apcu; fi
  - phpenv config-add tests/apc.ini
  - composer update --no-interaction --prefer-stable
  - php -i | grep 'apc'

script:
  - vendor/bin/phpunit
