language: php

sudo: false

matrix:
  include:
    - php: 5.6
      env: INSTALL_APCU="yes"
    - php: 7.0
      env: INSTALL_APCU="yes"
    - php: 7.1
      env: INSTALL_APCU="yes"
before_script:
  - composer update --no-interaction --prefer-stable
  # Enable additional PHP extensions
  - if [ "$INSTALL_APCU" == "yes" ] && [ "$TRAVIS_PHP_VERSION" = "5.*" ]; then printf "\n" | pecl install apcu-4.0.10 && phpenv config-add tests/apcu-5.6.ini; fi
  - if [ "$INSTALL_APCU" == "yes" ] && [ "$TRAVIS_PHP_VERSION" = "7.*" ]; then printf "\n" | pecl install apcu-beta && phpenv config-add tests/apcu-7.0.ini; fi

script:
  - vendor/bin/phpunit