language: php

sudo: false

php:
- 5.6
- 7.0
- 7.1

before_script:
  - if [ "$TRAVIS_PHP_VERSION" = "5.*" ]; then printf "\n" | pecl install apcu-4.0.10 && phpenv config-add tests/apcu-$TRAVIS_PHP_VERSION.ini; fi
  - if [ "$TRAVIS_PHP_VERSION" = "7.*" ]; then printf "\n" | pecl install apcu-beta && phpenv config-add tests/apcu-$TRAVIS_PHP_VERSION.ini; fi
  - composer update --no-interaction --prefer-stable;

script: vendor/bin/phpunit