language: php
dist: trusty
php:
- 5.6
- 7.0
- 7.1

sudo: false

before_install: phpenv config-add tests/$TRAVIS_PHP_VERSION.ini

install:
- composer update --no-interaction --prefer-stable;

script: vendor/bin/phpunit