language: php
dist: trusty
php:
- 5.6
- 7.0
- 7.1

sudo: false

before_script:
  - ./tests/res/install-apcu.sh
  - phpenv config-add tests/res/$TRAVIS_PHP_VERSION.ini
  - phpenv config-add tests/res/apc.ini

install:
- composer update --no-interaction --prefer-stable;

script: vendor/bin/phpunit