language: php
dist: trusty
php:
- 5.6
- 7.0
- 7.1

sudo: false

before_script:
  - if [[ $TRAVIS_PHP_VERSION = "5.6" ]]; then echo yes | pecl install apcu-4.0.11; fi
  - if [[ $TRAVIS_PHP_VERSION = "7.0" ]]; then echo yes | pecl install apcu-5.1.5; fi
  - if [[ $TRAVIS_PHP_VERSION = "7.1" ]]; then echo yes | pecl install apcu-5.1.8; fi

install:
- composer update --no-interaction --prefer-stable;

script: vendor/bin/phpunit